### ISSUE TITLE
CentOS 7

### ISSUE THREAD

**Issue by Ilia1** [sam88651/UsbHasp#1]
I need help. Tell me why it does not work.
Is the hasp key written correctly?
https://pastebin.com/PgWzuVP8

lsusb -v
https://pastebin.com/Y57Std8m

/var/log/messages
https://pastebin.com/BJbKyMqm

uname -a
`Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

I checked the work of the emulator here localhost:1947/\_int_/devices.html 
Installed haspd from Etersoft

**Comment by warlomak** [comment]
i can't see keys in hasplm too...

**Comment by Ilia1** [comment]
I have identified the presence of the key with the program eterkeytest

**Comment by warlomak** [comment]
local hasp 08ed1e32 work fine, but network 1B93C5D6 has issues...

**Comment by Ilia1** [comment]
![scrin](https://user-images.githubusercontent.com/16576224/51250229-902ba600-19b7-11e9-8314-e3416be57211.png)
I am fine. describe the problem, you can write to the email

**Comment by warlomak** [comment]
check email...
